apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: xenogeneic-basilisk-go-gitops
  description: This is GitOps manifest for xenogeneic-basilisk-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: xenogeneic-basilisk-go
    janus-idp.io/tekton: xenogeneic-basilisk-go 
    backstage.io/kubernetes-id: xenogeneic-basilisk-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:xenogeneic-basilisk-go
